### ISSUE TITLE
Import data from CSV / JSON

### ISSUE THREAD

**Issue by StigUtson** [allcount/allcountjs#103]
Does this framework support importing data from CSV / JSON files? 
If not is it possible to implement a new button that supports this feature?

**Comment by paveltiunov** [comment]
@StigUtson, although we don't have such feature at the moment it can be implemented using attachments field and action that parses it.

**Comment by StigUtson** [comment]
Thank you for your answer. How would I mange to attach/upload a file? Is there an API for that?

**Comment by paveltiunov** [comment]
You could use attachment field: https://allcountjs.com/docs/apps#primitive-types
It still seems like a workaround though if you want to upload and parse files on the fly. In this case you could write your own express route. 
Some example code how it can be done here:
https://github.com/allcount/allcountjs/blob/master/services/config/routes-setup.js#L85
https://github.com/allcount/allcountjs/blob/master/routes/crud.js#L137
