### ISSUE TITLE
Reuse authentication middleware

### ISSUE THREAD

**Issue by IGZgustavomarin** [allcount/allcountjs#108]
I'm using my own express server as shown in the examples. But I'd like to have other endpoints protected with the same authentication credentials. 

Is it possible to reuse the authentication methods as standalone middleware to protect routes external to AllcountJS? Ex: `/other/route/protected`

**Comment by paveltiunov** [comment]
Yep. You could use `appAccessRouter` as in the example below:
https://github.com/allcount/allcountjs/blob/master/routes/integrations-route.js
https://github.com/allcount/allcountjs/blob/c35e61effdd1f58c215b527f76e5b19201d7db62/allcount-server.js#L66
