### ISSUE TITLE
Debug messages in hooks

### ISSUE THREAD

**Issue by IGZgustavomarin** [allcount/allcountjs#114]
Is it possible to add `console.log` or a logger service inside `beforeSave` or other hooks? Any example?

**Comment by paveltiunov** [comment]
@IGZgustavomarin it's possible now. Just use `Console` dependency in crud hook.

**Comment by CreativeWolf** [comment]
@IGZgustavomarin Here's an example if it helps...

```
beforeSave: function(Entity, Crud, Console) {
          Console.log(Entity.applicantstatus.name);
          Console.log(Entity.applicantstatus.id);
}
```

**Comment by IGZgustavomarin** [comment]
thanks!

**Comment by nick13jaremek** [comment]
Hey there @paveltiunov @CreativeWolf 

I cannot see the log messages that are supposed to be printed based on the provided example.
On my beforeSave hook I am doing the following:
````
beforeSave: function(Entity, Dates, Console) {
  Console.log('beforeSave');
  Entity.startDate = Dates.moment().endOf('day');
}
````

However, I do not see the `beforeSave` string in the terminal or in the browser's JS console. Is there anything else that needs to be done beforehand to enable the `Console` service? Perhaps some config parameter?

Thanks in advance!
