### ISSUE TITLE
How to add extra validation on hook

### ISSUE THREAD

**Issue by IGZgustavomarin** [allcount/allcountjs#115]
Is it possible to add extra validation inside a hook? i.e.: 

```
      beforeSave: function (Entity) {
         if (Entity.someValue > 10000) {
            throw new Exception("someValue is wrong"); 
         }
      }
```
I've also tried to return a rejected Promise, as the docs says, but I can't prevent saving.

**Comment by paveltiunov** [comment]
@IGZgustavomarin you can add `ValidationError` dependency and throw it as follows:
`throw new ValidationError({field: "field error message"})`
