### ISSUE TITLE
How to do this in AllCountJS

### ISSUE THREAD

**Issue by waygee** [allcount/allcountjs#12]
I would like to create an admin tool for a rest api system that I am building in node.

So I would like admins to add companies and users.  However, I would like to add a password field for users that will be encrypted when it is stored.

This is what I came up with so far:

```javascript
A.app({
  appName: "Admin Tool",
  menuItems: [
    {
      name: "Companies",
      entityTypeId: "company",
    },
    {
      name: "Users",
      entityTypeId: "users",
    },

  ],
  entities: function(Fields) {
    return {
      company: {
        fields: {
          name: Fields.text("Name"),
          address1: Fields.text("Address1"),
          address2: Fields.text("Address2"),
          city: Fields.text("City"),
          state: Fields.text("State"),
          zip: Fields.text("Zip")
        },
	referenceName: "name",
      },
      users: {
        fields: {
          username: Fields.text("User Name"),
          email: Fields.text("email"),
          company: Fields.fixedReference("company", "company"),
          password: Fields.text("Password")
        }
      }
    }
  }
});
```
Is it possible to add a hook so that I can encrypt the password using a nodejs function that I provide?  How would I go about doing this?

**Comment by paveltiunov** [comment]
There are some options to do it:
1. You could reuse default entity type named `User`. This entity type is used to authenticate and authorize users accessing AllcountJS application. It has default fields `username`, `passwordHash` and fields for setting roles. If you define your own `User` entity type it would have a prototype from default `User`. So you could override `fields` property or add view for it using `views` property to define a `company` field. You could see an User Profile demo in [Demos Gallery](http://allcountjs.com/entity/DemoGallery) for example code.
2. There is `Fields.password()` field you could use to create your own password fields for any entity type you want. It uses SHA1 HMAC to create password hash salted with entity `id` field.
3. If SHA1 doesn't make sense for you then it could be overridden in `storageDriver` as described in [Extending docs](https://allcountjs.com/docs/server#overriding-dependencies)
```
injection.overrideFactory('storageDrive', 'oldStorageDriver', function (oldStorageDriver) {
    oldStorageDriver.passwordHash = function (objectId, password) {
        // calculate some hash
        return hash;
    }
    return oldStorageDriver;
})
```

**Comment by paveltiunov** [comment]
Hey waygee, does it work for you? Could we close the issue? Please share your experience.

**Comment by waygee** [comment]
Hi Pavel,

Thanks for your answer.  Because of time constraints on my current project, I was not able to follow through with the implementation using allcount.js.  I appreciate you taking the time to answer my question and for developing a great tool.
