### ISSUE TITLE
Server Crash (Local) with demo project

### ISSUE THREAD

**Issue by thinklightswitch** [allcount/allcountjs#15]
After following the steps here: https://github.com/allcount/allcountjs

The server crashes frequently.

The MongoDB database was created correctly

maverick:allcountjs-helloworld nomad$ allcountjs --git file:///Users/nomad/allcountjs-helloworld --db mongodb://localhost:27017/allcountjs-helloworld
Application server for "file:///Users/nomad/allcountjs-helloworld" listening on port 9080
/Users/nomad/.node/lib/node_modules/allcountjs/node_modules/q/q.js:126
                    throw e;
                          ^
Error: Command failed: /bin/sh -c git log HEAD^..HEAD
fatal: ambiguous argument 'HEAD^..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

I installed "q" globally to see if it will help

EDIT:

It looks like the path for the git repo is the issue
allcountjs --git file:///Users/nomad/allcountjs-helloworld --db mongodb://localhost:27017/allcountjs-helloworld
This is what I used - it launches but fails soon

**Comment by paveltiunov** [comment]
Hello thinklightswitch!
Thanks for filing this!
There is a bug in last revision hash retrieval of git repository if there is only one commit. Nice catch!
Will push fix soon.

**Comment by paveltiunov** [comment]
Released 1.11.2. Please check does it work for you? Thanks!
