### ISSUE TITLE
Not loading the helloworld-app.js file

### ISSUE THREAD

**Issue by andrenventer** [allcount/allcountjs#17]
$ allcountjs --git file://helloworld-app --db mongodb://localhost:27017/helloworld-app-db
Failed to fetch "file://helloworld-app". Trying to use as regular directory.

$ allcountjs --git file://helloworld-app.js --db mongodb://localhost:27017/helloworld-app-db
Failed to fetch "file://helloworld-app.js". Trying to use as regular directory.

The app configuration file fails to load.

current directory is $ allcountjs-helloworld

**Comment by andrenventer** [comment]
This works

$ allcountjs --git ./ --db mongodb://localhost:27017/helloworld-app-db
Application server for "./" listening on port 9080

https://allcountjs.com/docs/getting-started suggested
allcountjs --git file://<path to allcountjs-helloworld> --db mongodb://localhost:27017/allcountjs-helloworld

**Comment by chikh** [comment]
Andre,

We've slightly changed the way of starting application and changed readme.md according to the solution of your problem. We'll update https://allcountjs.com/docs/getting-started soon.

Thank you for your response, we really appreciate that!

**Comment by andrenventer** [comment]
FYI --app from the readme does not currently work - its still --git
I guess that is in transition

**Comment by paveltiunov** [comment]
Hi Andre!

Thank you for your feedback!

Have you tried to update allcountjs using `npm install -g allcountjs`?

**Comment by andrenventer** [comment]
I did and then it changed - of course :)
I started reading the source code, so now I see what you are doing with git url and file location.
Will dig deeper tomorrow.

Excellent project!

**Comment by paveltiunov** [comment]
Andre, good to hear that!
Thanks!
