### ISSUE TITLE
Reference field in relation hangs browser while editing

### ISSUE THREAD

**Issue by paveltiunov** [allcount/allcountjs#32]

**Comment by AlexYegupov** [comment]
Guys, any news? Bug seems very critical.

 Reproduced in:
  google chrome Версия 45.0.2454.85 (64-bit) ,
  opera 31.0.1889.174
System: Ubuntu 14.04.3 LTS (x86_64; fluxbox)

How to reproduce:
1. Open "POS and inventory" demo
2. Items -> "Coffee" -> edit -> press [+] to add transaction
3. After that browser is hanging and in consle we can see:
GET https://demo-3fa27674d1.allcountjs.com/assets/less/select2.png 404 (Not Found)
and increasing error index

Thanks.

**Comment by paveltiunov** [comment]
Hi @AlexYegupov ! Thanks for remind! It's fixed. Will release new npm release soon.
