### ISSUE TITLE
Other foreign keys strategy support?

### ISSUE THREAD

**Issue by AlexYegupov** [allcount/allcountjs#51]
It's rather question then issue. Please correct me if there is better place to put that ones.

It seems that allcountjs implements "simple foreign keys" stragegy of storing one-to-many related data (like Order - OrderItems). 

Is there are (or not) any plans to support other relationship options like "using an array of foreign keys" or "using embedded entities" in other products (http://ng-admin-book.marmelab.com/doc/Relationships.html)?

Thanks.

**Comment by paveltiunov** [comment]
@AlexYegupov thanks for asking that!
We actually do support array of foreign keys using `multiReference` field: https://allcountjs.com/docs/apps#relationships. For embedded documents we already have an issue: https://github.com/allcount/allcountjs/issues/21
