### ISSUE TITLE
Support for Indian Rupee Sign ₹

### ISSUE THREAD

**Issue by CreativeWolf** [allcount/allcountjs#65]
Need support for Indian Rupee Sign ₹ please.

**Comment by paveltiunov** [comment]
@CreativeWolf could you please elaborate on issue when you use this sign?

**Comment by paveltiunov** [comment]
You'd need to add localization for Indian: https://github.com/allcount/allcountjs/blob/master/docs/configuring.md
Please see localization section.

**Comment by CreativeWolf** [comment]
Thank you for that clarification.
