### ISSUE TITLE
Primitive Field Type Fields.email(name)

### ISSUE THREAD

**Issue by CreativeWolf** [allcount/allcountjs#82]
It'd be good to have a Primitive Field Type Fields.email(name)

**Comment by paveltiunov** [comment]
@CreativeWolf like text field with email pattern validation?

**Comment by CreativeWolf** [comment]
Yes, that'd help :)

**Comment by CreativeWolf** [comment]
@matteocng Firstly, Thank you for addressing this. Just  a request, I understand Angular's default validation has issues with pattern recognition - https://github.com/angular/angular.js/issues/5899 - Not sure if that's been changed now and I might be completely bringing up an unwarranted issue. 
Just in case, if we are to use pattern, this seems to cover the bases:

return $compile('<input type="email" ng-model="emailValue" ng-pattern="/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/" class="form-control">')(scope);

References: 
https://github.com/angular/angular.js/issues/5899
http://www.w3resource.com/javascript/form/email-validation.php

Looking forward to your feedback.

Thanks!

**Comment by paveltiunov** [comment]
@CreativeWolf nice point! Yep. As the issue requests we need some email validation. So we can start with client side validation as @CreativeWolf proposed. But I doubt solution with `ng-pattern` is user friendly in this context.

**Comment by matteocng** [comment]
Thank you @CreativeWolf for bringing up the issue, I personally find [this] (/angular/angular.js/issues/5899#issuecomment-60141093) argument compelling as far as using the default, Chromium derived regex goes. Perhaps adding a layer of server side, non-pattern based validation could be a future evolution (e.g domain, mx, smtp, third party api).

**Comment by CreativeWolf** [comment]
Fair point indeed. However, in an environment to have some user control, it becomes essential. Of course, as far as there is an option to use ng-pattern or Chromium derived regex or a custom pattern on the fly in a framework like AllcountJS will be highly useful.

**Comment by paveltiunov** [comment]
Interesting. @matteocng have you checked that native browser email validation works both in a form and in the grid? It could be a solution.

**Comment by matteocng** [comment]
@paveltiunov as far as i know a form is needed to get the native UI validation behaviour (native tooltip with natively generated message). @CreativeWolf I agree that letting users add their own custom logic/pattern on top of AllcountJS default validation would be a very useful feature, albeit more complex to implement well. What would you think of a regex('...', 'Message') method in the context of [#4] (4#issuecomment-154178148)?

**Comment by paveltiunov** [comment]
@matteocng just checked current behavior. It actually checks but in case email has wrong format it just doesn't save. It would be nice to notify user somehow that email has wrong format. Native tooltip doesn't appear for me. 
How do you think?

**Comment by matteocng** [comment]
@paveltiunov nice find, I've reproduced that behaviour. If you ran the app below, inserted 'a' in all six email, link and quantity fields and saved, the red error label 'Required' would just appear below the required() fields. Then, if you correctly filled in just the three required() fields, the save action would complete by saving 'null' in the DB for the three optional fields. As you correctly pointed out, it would be nice to 1) block the save action if invalid data was inserted in an optional field, showing an error label below it 2) change the 'Required' error label with a different message when the issue was a validation error; this change would affect both required and optional fields.

    A.app({
      appName: "Validation behaviour",
      appIcon: "heart",
      menuItems: [
        {
          name: "Gifts",
          icon: "gift",
          entityTypeId: "Gift",
        }
      ],
      entities: function(Fields) {
        return {
          Gift: {
            title: 'Gifts',
            fields: {
              item: Fields.text("Item").required(),
              quantity: Fields.integer("Quantity"),
              quantity_required: Fields.integer("Quantity Required").required(),
              email: Fields.email("Email"),
              email_required: Fields.email("Email Required").required(),
              link: Fields.email("Link"),
              link_required: Fields.email("Link Required").required()
            }
          }
        }
      }
    });

**Comment by paveltiunov** [comment]
@matteocng Ah. I see. Nice workaround with `required()`. It might work for many situations. Do you think we need another issue for validation?

**Comment by matteocng** [comment]
@paveltiunov Yes, moved to #91.

**Comment by paveltiunov** [comment]
@matteocng Ok. Nice. Will close this one then.
