### ISSUE TITLE
I can't signup

### ISSUE THREAD

**Issue by cedced19** [allcount/allcountjs#90]
Hi,
I can't signup when I put on the button it doesn't work
When I was reading HTML code I was upset that there is no `<form>`, but you use:

````javascript
$('form').submit();
```
[Source](https://github.com/allcount/allcountjs/blob/master/public/assets/js/login.js#L18)

Is it the origin of the problem or there is an other?

Thank you for this great software.

**Comment by paveltiunov** [comment]
Hi @cedced19 !
Thank you for your great feedback!

`$('form').submit();` actually performs sign in operation. There is `<form>` it references:
https://github.com/allcount/allcountjs/blob/master/views/login.jade#L4

Could you please provide your source code so we can help you with it?
